config/routes.rb
FirehoseApp::Application.routes.draw do

   root 'static_pages#index'

   resources :pics

end

app/models/pic.rb
class Pic < ActiveRecord::Base
	mount_uploader :image, ImageUploader


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pics_controller.rb
class PicsController < ApplicationController

	def index
		@pics = Pic.all
	end

	def new
		@pic = Pic.new
	end

	def create
		@pic = Pic.create( pic_params )
		redirect_to pics_path
	end 

	private

	def pic_params
		params.require(:pic).permit(:lesson, :emotion, :learned, :image)
	end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

	def index
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pics_helper.rb
module PicsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FirehoseApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="navbar navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
 
      <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
 
      <!-- Be sure to leave the brand out there if you want it shown -->
      <%= link_to 'Firehose App', root_path, :class => 'brand' %>
 
      <!-- Everything you want hidden at 940px or less, place within here -->
      <div class="nav-collapse collapse">
        <!-- .nav, .navbar-search, .navbar-form, etc -->

        <ul class="nav">
        	<li>
        		<%=	link_to 'My App', pics_path %>
        	</li>

          <li>
            <%= link_to 'Add a New Pic', new_pic_path %>
          </li>

        </ul>

      </div>
 
    </div>
  </div>
</div>	

<%= yield %>

</body>
</html>

app/views/pics/index.html.erb
	<% @pics.each do |pic| %>

	<div class="boxy span3">
		<h1 class="custom-h1">
			Lesson: <%= pic.lesson %>
		</h1>

		<%= image_tag pic.image %>
		<br />
		
		<h2>
			Emotion: <%= pic.emotion %>
		</h2>
		<h2>
			Learned: <%= pic.learned %>
		</h2>
	</div>

	<% end %>

app/views/pics/new.html.erb
<div class="boxy span6 offset3 text-center">
	<h2>Upload your Image</h2>
	<%= simple_form_for @pic do |f| %>

		<%= f.input :lesson, label: 'Enter the lesson number' %>
		<br/>
		<%= f.input :emotion, label: 'Tell me how you felt', placeholder: 'e.g. happy, stoked, great, fantastic, etc.' %>
		<br/>
		<%= f.input :learned, label: 'What did you learn', placeholder: 'e.g. HTML5, CSS3, Rails, Ruby, Github, Heroku, etc.' %>
		<br/>

		<%= f.input :image, label: 'Upload your image', as: :file %>
		<br/>

		<%= submit_tag 'Save', :class => 'btn btn-warning btn-large' %>
	<% end %>
</div>

app/views/static_pages/index.html.erb
<div class="boxy span6 offset3 text-center">

	<h1 class="custom-h1">My Web Development Journey</h1>

	<br/>

	<h2>Turning ideas into reality</h2>

	<br/>


	<%= link_to 'Launch my App', pics_path, :class => 'btn btn-warning btn-large' %>

</div>